/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VoteSystem;

import static VoteSystem.VoterInfo.demail;
import static java.sql.JDBCType.VARCHAR;
import static java.sql.Types.VARCHAR;
import java.util.Properties;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.mail.*;
import java.sql.*;
import javax.mail.internet.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class InfoEmail extends javax.swing.JFrame {
    static String rname, rcnic, rage, rstate, rcity, remail, rcand, rvote;

    /**
     * Creates new form InfoEmail
     */
    public InfoEmail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cityfield = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        label2 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        statefield = new javax.swing.JTextField();
        cnicfield = new javax.swing.JTextField();
        agefield = new javax.swing.JTextField();
        invalidmail = new javax.swing.JLabel();
        votefield = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        recieveemail = new javax.swing.JButton();
        back = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(49, 49, 49));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VoteSystem/icons8_unread_messages_200px.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Prompt ExtraBold", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("REVIEW INFO");

        jPanel1.setBackground(new java.awt.Color(186, 79, 84));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel2.setBackground(new java.awt.Color(49, 49, 49));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REVIEW INFORMATION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Prompt ExtraBold", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(202, 62, 71));

        jLabel7.setFont(new java.awt.Font("Raleway ExtraBold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("City");

        cityfield.setEditable(false);
        cityfield.setBackground(new java.awt.Color(255, 255, 255));
        cityfield.setFont(new java.awt.Font("Raleway SemiBold", 0, 11)); // NOI18N
        cityfield.setToolTipText("");
        cityfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cityfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cityfieldFocusLost(evt);
            }
        });
        cityfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cityfieldKeyPressed(evt);
            }
        });

        email.setText("email@domain.com");
        email.setToolTipText("Please enter your email under a valid domain.");
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailKeyPressed(evt);
            }
        });

        label2.setFont(new java.awt.Font("Raleway ExtraBold", 0, 12)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Your Info:");

        label1.setFont(new java.awt.Font("Raleway ExtraBold", 0, 12)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Please enter your email:");

        jLabel1.setFont(new java.awt.Font("Raleway ExtraBold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Raleway ExtraBold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CNIC");

        jLabel3.setFont(new java.awt.Font("Raleway ExtraBold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Age");

        jLabel4.setFont(new java.awt.Font("Raleway ExtraBold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("State");

        namefield.setEditable(false);
        namefield.setBackground(new java.awt.Color(255, 255, 255));
        namefield.setFont(new java.awt.Font("Raleway SemiBold", 0, 11)); // NOI18N
        namefield.setToolTipText("");
        namefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                namefieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                namefieldFocusLost(evt);
            }
        });
        namefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefieldActionPerformed(evt);
            }
        });
        namefield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                namefieldKeyPressed(evt);
            }
        });

        statefield.setEditable(false);
        statefield.setBackground(new java.awt.Color(255, 255, 255));
        statefield.setFont(new java.awt.Font("Raleway SemiBold", 0, 11)); // NOI18N
        statefield.setToolTipText("");
        statefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                statefieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                statefieldFocusLost(evt);
            }
        });
        statefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statefieldActionPerformed(evt);
            }
        });
        statefield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                statefieldKeyPressed(evt);
            }
        });

        cnicfield.setEditable(false);
        cnicfield.setBackground(new java.awt.Color(255, 255, 255));
        cnicfield.setFont(new java.awt.Font("Raleway SemiBold", 0, 11)); // NOI18N
        cnicfield.setToolTipText("");
        cnicfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cnicfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cnicfieldFocusLost(evt);
            }
        });
        cnicfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnicfieldActionPerformed(evt);
            }
        });
        cnicfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cnicfieldKeyPressed(evt);
            }
        });

        agefield.setEditable(false);
        agefield.setBackground(new java.awt.Color(255, 255, 255));
        agefield.setFont(new java.awt.Font("Raleway SemiBold", 0, 11)); // NOI18N
        agefield.setToolTipText("");
        agefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                agefieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                agefieldFocusLost(evt);
            }
        });
        agefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agefieldActionPerformed(evt);
            }
        });
        agefield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                agefieldKeyPressed(evt);
            }
        });

        invalidmail.setFont(new java.awt.Font("Raleway ExtraBold", 0, 12)); // NOI18N
        invalidmail.setForeground(new java.awt.Color(255, 255, 255));
        invalidmail.setText("Invalid Email ID");
        invalidmail.setVisible(false);

        votefield.setEditable(false);
        votefield.setBackground(new java.awt.Color(255, 255, 255));
        votefield.setFont(new java.awt.Font("Raleway SemiBold", 0, 11)); // NOI18N
        votefield.setToolTipText("");
        votefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                votefieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                votefieldFocusLost(evt);
            }
        });
        votefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                votefieldActionPerformed(evt);
            }
        });
        votefield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                votefieldKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Raleway ExtraBold", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Vote");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(6, 6, 6))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(10, 10, 10))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(1, 1, 1))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(10, 10, 10))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(10, 10, 10)))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namefield, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cityfield, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statefield, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cnicfield, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(agefield, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(votefield, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(invalidmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(53, 53, 53))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {agefield, cityfield, cnicfield, namefield, statefield, votefield});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(invalidmail, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namefield, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnicfield, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(agefield, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(statefield, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(votefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {agefield, cityfield, cnicfield, namefield, statefield, votefield});

        recieveemail.setBackground(new java.awt.Color(255, 255, 255));
        recieveemail.setFont(new java.awt.Font("Raleway SemiBold", 0, 12)); // NOI18N
        recieveemail.setText("Recieve Email");
        recieveemail.setEnabled(false);
        recieveemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recieveemailActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("Raleway SemiBold", 0, 12)); // NOI18N
        back.setText("Return to Voter's Main Screen");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        submit.setBackground(new java.awt.Color(255, 255, 255));
        submit.setFont(new java.awt.Font("Raleway SemiBold", 0, 12)); // NOI18N
        submit.setText("Submit Email");
        submit.setToolTipText("");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(recieveemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(submit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {back, recieveemail, submit});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recieveemail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {back, recieveemail, submit});

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cityfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityfieldFocusGained

    }//GEN-LAST:event_cityfieldFocusGained

    private void cityfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityfieldFocusLost

    }//GEN-LAST:event_cityfieldFocusLost

    private void cityfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityfieldKeyPressed

    }//GEN-LAST:event_cityfieldKeyPressed

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        if(email.getText().trim().toLowerCase().equals("email@domain.com")){
            email.setText("");}
    }//GEN-LAST:event_emailFocusGained

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        if(email.getText().trim().equals("") || email.getText().trim().toLowerCase().equals("email@domain.com")){
            email.setText("email@domain.com");}
    }//GEN-LAST:event_emailFocusLost

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed

    }//GEN-LAST:event_emailActionPerformed

    private void emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyPressed

    }//GEN-LAST:event_emailKeyPressed

    private void namefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namefieldFocusGained

    }//GEN-LAST:event_namefieldFocusGained

    private void namefieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namefieldFocusLost

    }//GEN-LAST:event_namefieldFocusLost

    private void namefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namefieldActionPerformed

    private void namefieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namefieldKeyPressed

    }//GEN-LAST:event_namefieldKeyPressed

    private void statefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_statefieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_statefieldFocusGained

    private void statefieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_statefieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_statefieldFocusLost

    private void statefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statefieldActionPerformed

    private void statefieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_statefieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_statefieldKeyPressed

    private void recieveemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recieveemailActionPerformed

        final String username = "muntaha";
        final String password = "muntaha18sw75";
        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.sarttls.enable", "true");
        props.put("mail.smtp.host", "mail.smtp2go.com");
        props.put("mail.smtp.port", "2525"); // 8025, 587 and 25 can also be used.

        Session session = Session.getInstance(props,new javax.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });
        try{

            Message m = new MimeMessage(session);

            m.setFrom(new InternetAddress("muntahamemon109@gmail.com"));
            m.setRecipients(Message.RecipientType.TO,
            InternetAddress.parse(remail));

            m.setSubject("Voting System Project: Voter's Details");

            m.setText("Below are the details stored of the emailed voter:"+ "\n"+ "\n" + "CNIC: "+rcnic+ "\n"+ "Name : "+rname+ "\n" + "Age: "+rage+ "\n"+ "State: "+rstate+"\n"+ "City : "+rcity+ "\n"+ "Vote Casted to: "+rcand+ "\n" + "\n" +"We're glad that you participated in our project."+ "\n"+ "Thankyou for your patience and support!");

            Transport.send(m);
            System.out.println("Done");
            JOptionPane.showMessageDialog(this, "Email delivered successfully!");
            setVisible(false);
        }

        catch(MessagingException e) {
            throw new RuntimeException(e);
        }

    }//GEN-LAST:event_recieveemailActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new VoterOptions().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void cnicfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnicfieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cnicfieldFocusGained

    private void cnicfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnicfieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cnicfieldFocusLost

    private void cnicfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnicfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnicfieldActionPerformed

    private void cnicfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnicfieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnicfieldKeyPressed

    private void agefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_agefieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_agefieldFocusGained

    private void agefieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_agefieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_agefieldFocusLost

    private void agefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agefieldActionPerformed

    private void agefieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agefieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_agefieldKeyPressed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        remail = email.getText();

        //-----------------------
        String email_pattern = "^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@"
        + "[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$";

        Pattern pattern = Pattern.compile(email_pattern);
        Matcher matcher = pattern.matcher(remail);

        if(matcher.matches() == false){ //Age and Email Limitations
            invalidmail.setVisible(true);
            return;
        }
        else{
            invalidmail.setVisible(false);
        }
        //-----------------------

        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/votingsystem","root","lunaaurora");
            Statement st=conn.createStatement();
            String sql = "SELECT * FROM voter WHERE email='"+remail+"';";
            ResultSet pstmt=st.executeQuery(sql);
            
            while(pstmt.next()){
            rname = pstmt.getString("name");
            rcnic = pstmt.getString("cnic");
            rage = String.valueOf(pstmt.getInt("age"));
            rstate = pstmt.getString("state");
            rcity = pstmt.getString("city");
            rcand = pstmt.getString("candidate");
            }
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            return;
        }

        namefield.setText(rname);
        cnicfield.setText(rcnic);
        agefield.setText(rage);
        statefield.setText(rstate);
        cityfield.setText(rcity);
        votefield.setText(rcand);
        recieveemail.setEnabled(true);

    }//GEN-LAST:event_submitActionPerformed

    private void votefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_votefieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_votefieldFocusGained

    private void votefieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_votefieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_votefieldFocusLost

    private void votefieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_votefieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_votefieldKeyPressed

    private void votefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_votefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_votefieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoEmail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agefield;
    private javax.swing.JButton back;
    private javax.swing.JTextField cityfield;
    private javax.swing.JTextField cnicfield;
    private javax.swing.JTextField email;
    private javax.swing.JLabel invalidmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JTextField namefield;
    private javax.swing.JButton recieveemail;
    private javax.swing.JTextField statefield;
    private javax.swing.JButton submit;
    private javax.swing.JTextField votefield;
    // End of variables declaration//GEN-END:variables
}
